spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jackson:
    serialization:
      write-dates-as-timestamps: false

cross-origin-addresses: http://localhost:3000
liquibase:
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  url: ${DB_URL}
