spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jackson:
    serialization:
      write-dates-as-timestamps: false

cross-origin-addresses: http://localhost:3000
liquibase:
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  url: ${DB_URL}

endpoints:
  health:
    path: /

security:
  oauth2:
    client:
      clientId: 518342583119-rflaovpanso3fks1eubnbmae55b6gdqd.apps.googleusercontent.com
      clientSecret: 2gxfbBt4EhbydWxBSeiXOojD
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
