spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jackson:
    serialization:
      write-dates-as-timestamps: false

cross-origin-addresses: http://localhost:3000
liquibase:
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  url: ${DB_URL}

endpoints:
  health:
    path: /

github:
    clientId: 40b8bbcbd569eb863c18
    clientSecret: 525d925f1a21ccf82093f14b7a96436fee513f01
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
