spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jackson:
    serialization:
      write-dates-as-timestamps: false

cross-origin-addresses: http://localhost:3000
liquibase:
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  url: ${DB_URL}

endpoints:
  health:
    path: /

keycloak:
  realm: admin
  auth-server-url: http://local.smartworkx.nl/auth
  resource: admin-api
  ssl-required: none
  credentials:
    secret: dc007938-7d82-4bce-b22f-0a2726f502e6
  bearer-only: true
  use-resource-role-mappings: true
  securityConstraints:
    - authRoles:
      - user
      securityCollections:
      - name: all
        patterns:
        - /*

logging:
  level:
    root: DEBUG

