spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.33.12:5432/admin
    username: admin-api
    password: password
  jackson:
    serialization:
      write-dates-as-timestamps: false

cross-origin-addresses: http://localhost:3000
liquibase:
  user: admin-owner
  password: password
  url: jdbc:postgresql://192.168.33.12:5432/admin


---

spring:
  profiles: test

---

spring:
  profiles: ci
  datasource:
    url: jdbc:postgresql://52.209.45.39:5432/admin
liquibase:
  url: jdbc:postgresql://52.209.45.39:5432/admin
server:
  port: 8081